### ISSUE TITLE
re-forking

### ISSUE THREAD

**Issue by dmercer2** [fdac/Assignment1#4]
Dr. Mockus,

I forked the original Assignment 1 repo over the weekend and completed the assignment. However, I would like to try the extra credit you have added since then. What is a good method for updating my Assignment1 repo? Whenever I try to fork again (in the hopes that it will just update my repo with the later version) it just takes me to my already existing repo.

Thank you,
David

**Comment by audrism** [comment]
You do no need to fork again. Here are the steps:
- you need to add [upstream repository](https://help.github.com/articles/configuring-a-remote-for-a-fork)
  git remote add upstream https://github.com/fdac/Assignment1
- Then [sync the fork](https://help.github.com/articles/syncing-a-fork)
  git fetch upstream
  git checkout master
  git merge upstream/master

Please let me know if it worked

**Comment by audrism** [comment]
In case you have a conflict the following is a great answer (getting 1068 thumbs
up on stackoverflow is amazing) 

http://stackoverflow.com/questions/161813/fix-merge-conflicts-in-git

Alternatively, you don't need to merge, instead:

```
git clone https://github.com/fdac/Assignment1 fdac_Assignment1
```

Then from your browser (localhost:8888) you can navigate to 
another notebook in  fdac_Assignment1
and copy/paste what you need back into your notebook.

**Comment by audrism** [comment]
Closing the issue as it seems to have been resolved.
